name: ci

on:
  push:
    branches:
      - actions
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip install -r requirements.txt
          python cv.py cv generate
          cp CNAME site/CNAME
          cd site
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "deploy"
          echo "https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git"
          git push -f "https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git" master:gh-pages
