name: ci

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync
          uv run cv html cv.yaml site
          uv run cv print cv.yaml site/print
          cp CNAME site/CNAME
          cd site
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "deploy"
          git push -f "https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git" master:gh-pages
